---
title: "FPL Dashboard - Sacagawea"
author: "Will Miller"
date: 'Last updated: `r format(Sys.Date(), "%d-%B-%Y")`'
output: html_document
---

```{r, echo = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(ggplot2)
library(data.table)
library(directlabels)
library(plotly)
library(grid)
library(ggthemes) # Load

setwd("~/fpl/fpl_saca")

#cleaning up data

df <- fread(file="data.csv", drop=1)

#removing some players and removing blank covid Gameweeks

df <- rename(df, Player = player_name) #For renaming dataframe column
df <- rename(df, Total_points = current.total_points)
df <- rename(df, Gameweek_points = current.points)
df <- rename(df, Gameweek = current.event)
df$value_m <- df$current.value/10
max_GW <- max(df$Gameweek)

GWleader <- subset(df,Gameweek==max_GW)
firstGW <- max(GWleader$Gameweek_points)
GWleader <- subset(df, Gameweek_points==firstGW)


first <- max(df$Total_points)
leader <- subset(df, Total_points==first)
l <- as.character(leader$Player)
tp <- as.numeric(leader$Total_points)

```

##Overview

`r l` is in first place with `r tp` points.  
`r GWleader$Player` scored highest in gameweek `r GWleader$Gameweek`, with `r GWleader$Gameweek_points` points.  

##Charts

```{r, echo = FALSE, message=FALSE, warning=FALSE, out.width="100%"}
p1 <- ggplot(df, aes(x = Gameweek, y = Total_points, colour = Player, group = Player)) + 
  geom_line() + 
  scale_colour_discrete(guide = 'none')  + 
  scale_x_continuous(breaks=seq(0, max_GW, 1), expand = c(0, 0)) +
  geom_dl(aes(label = Player), method = list(dl.trans(x = x + .3), "last.bumpup")) +
  theme_bw() +
  theme(plot.margin = unit(c(1,4,1,1), "lines"))

# Code to turn off clipping
gt1 <- ggplotGrob(p1)
gt1$layout$clip[gt1$layout$name == "panel"] <- "off"
grid.draw(gt1)

```

```{r, echo = FALSE, message=FALSE, warning=FALSE, out.width="100%"}
 p2 <- ggplot(df, aes(x = Gameweek, y = value_m, colour = Player, group = Player)) +
   geom_line() +
   scale_colour_discrete(guide = 'none')  +
   scale_x_continuous(breaks=seq(0, max_GW, 1), expand = c(0, 0)) +
   geom_dl(aes(label = Player), method = list(dl.trans(x = x + .3), "last.bumpup")) +
   theme_bw() +
   theme(plot.margin = unit(c(1,4,1,1), "lines"))

 # Code to turn off clipping
 gt2 <- ggplotGrob(p2)
 gt2$layout$clip[gt1$layout$name == "panel"] <- "off"
grid.draw(gt2)


# Bar chart - bench points

bp <- ggplot(df,aes(x=reorder(Player,current.points_on_bench), y=current.points_on_bench)) + geom_bar(stat='Identity') 
bp <- bp + ggtitle("Bench points") +ylab('Points on bench') + xlab('Player')
bp <- bp + theme_hc()+ scale_colour_hc() + theme(legend.position = "none") + coord_flip()
bp

# Bar chart - Transfers made

tm <- ggplot(df,aes(x=reorder(Player,current.event_transfers), y=current.event_transfers)) + geom_bar(stat='Identity') 
tm <- tm + ggtitle("Transfers") + xlab('Player') + ylab('Transfers') + scale_y_continuous(breaks=seq(0, 40, 2))
tm <- tm + theme_hc()+ scale_colour_hc() + theme(legend.position = "none") + coord_flip()
tm


# Bar chart - Transfer spend

ts <- ggplot(df,aes(x=reorder(Player,current.event_transfers_cost), y=current.event_transfers_cost)) + geom_bar(stat='Identity') 
ts <- ts + ggtitle("Transfer spend") +ylab('Transfer spend') + xlab('Player') + scale_y_continuous(breaks=seq(0, 40, 2))
ts <- ts + theme_hc()+ scale_colour_hc() + theme(legend.position = "none") + coord_flip()
ts

```



